apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: space
  template:
    metadata:
      labels:
        app: space
    spec:
      containers:
      - name: space
        image: bharathg125/spaceproject:v33
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
